### ISSUE TITLE
Using Test::Approx::is_approx is problematic

### ISSUE THREAD

**Issue by eserte** [yanick/Term-Caca#4]
On some of my smoker systems the `t/basic.t` test fails:
```
#   Failed test 'render time around 1s'
#   at t/basic.t line 72.
#   test: '0.999767' =~ '1'
#   error: edit distance (8) was greater than threshold (0.5)
# Looks like you failed 1 test of 4.
t/basic.t .............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
```

Problem is that `Test::Approx::is_approx` is using `POSIX::strtod` for determining the type of its arguments, and `strtod` is sensitive to the locale. So if a locale with a comma radix (e.g. `LC_ALL=de_DE.UTF-8`) is used, the floats are recognized as strings and instead of a approximative numeric check a levenshtein distance test is done. This is an old known issue: https://rt.cpan.org/Ticket/Display.html?id=84499

Even using `is_approx_num` does not help, as this function also uses `strtod`, so the float is recognized as an int, so we would get:
```
#   Failed test 'render time around 1s'
#   at t/basic.t line 72.
#   test: '0' =~ '1'
#   error: distance (1) was greater than threshold (0.5)
```
Maybe using just basic `cmp_ok` and `abs` is better here, e.g.
```
diff --git a/t/basic.t b/t/basic.t
index a933790..4fd819b 100644
--- a/t/basic.t
+++ b/t/basic.t
@@ -5,7 +5,6 @@ use warnings;
 # testing
 
 use Test::More;
-use Test::Approx;
 
 use Term::Caca::Constants qw/ :colors /;
 use Term::Caca;
@@ -69,7 +68,7 @@ my $render_time = $t->rendering_time;
 
 # render time should be ~ 1 second
 
-is_approx $render_time, 1, 'render time around 1s', '0.5';
+cmp_ok abs($render_time-1), "<", 0.5, 'render time around 1s';
 
 pass 'reached the end';
 
```

**Comment by yanick** [comment]
Thanks for that! Test modified and new release punted to CPAN!
